name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker-compose build
      - name: Lint with flake8
        run: |
          docker-compose run gbbox make lint
      - name: Run tests
        run: |
          docker-compose run gbbox make test
