name: Lint and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
