name: Publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
      - name: Publish to PYPI
        run: |
          echo "Token should be masked..."
          echo "$PYPI_API_TOKEN"
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
